name: "Telegram to RSS Action"
description: "Create RSS feed from Telegram channel"
author: "Taras Drapalyuk"
branding:
  icon: "rss"
  color: "blue"
inputs:
  output-dir:
    description: "Output directory path for RSS feed. 
                  If not specified, output file will be created in current directory."
    default: "./"
  formats:
    description: "Output formats separated by comma. 
                  Excepted formats: `rss`, `atom`, `json`"
    default: "rss"
  telegram-channels:
    description: "Telegram channels separated by comma. 
                  Excepted formats: `@channel`, `channel` or `https://t.me/channel`"
    default: "@telegram"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/kulapard/tg2feed:main"
