name: "Telegram Feed Builder GitHub Action"
description: "Create feed from Telegram channels"
author: "Taras Drapalyuk"
branding:
  icon: "rss"
  color: "blue"
inputs:
  output-dir:
    description: "Output directory path for feeds. 
                  If not specified, output files will be created in current directory."
    default: "./"
  formats:
    description: "Output formats separated by comma. 
                  Accepted formats: `rss`, `atom`, `json`"
    default: "rss"
  telegram-channels:
    description: "Telegram channels separated by comma. 
                  Accepted formats: `@channel`, `channel` or `https://t.me/channel`"
    default: "@telegram"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/kulapard/tg2feed:main"
