name: test action

on:
  push:
    branches:
      - 'main'
    paths: # to run only on changes in the action file
      - 'action.yml'

# one running workflow per branch, others will wait
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-action:
    needs: [ build-image ]
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
    steps:
      - uses: actions/checkout@v4
      - name: Create RSS feed
        uses: ./
        with:
          output-dir: ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT_FILENAME }}
          formats: "xml,json"
          telegram-channels: "@telegram"

      - name: Check RSS feed file exists
        run: |
          test -f "${{ env.OUTPUT_DIR }}/feed.xml"
          test -f "${{ env.OUTPUT_DIR }}/feed.json"