name: Build feed
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# one running workflow per branch, others will wait
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  OUTPUT_DIR: './pages'

jobs:
  build-feed:
    permissions:
      id-token: write  # to use pages
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Create feed
        uses: kulapard/tg2feed@main
        with:
          output-dir: ${{ env.OUTPUT_DIR }}
          formats: "rss,atom,json"
          telegram-channels: "@Alexey_Pivo_varov,@addmeto,@kyrillic,@dukaliti,@pmdaily"

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT_DIR }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
